# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('position_type', models.CharField(choices=[('O', 'Officer'), ('A', 'Advisor'), ('C', 'Chair')], default='C', max_length=1)),
                ('email', models.CharField(default='hkn-officers@umich.edu', max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Member')),
            ],
        ),
    ]
