# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='email',
            field=models.CharField(default='hkn-officers@umich.edu', max_length=100),
        ),
    ]
