# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_leader_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
