# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcafe', '0002_auto_20160204_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id_number',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
