# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electee',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Member')),
                ('num_socials_approved', models.IntegerField(default=0)),
                ('num_socials_total', models.IntegerField(default=0)),
                ('num_service_hours_approved', models.IntegerField(default=0)),
                ('num_service_hours_total', models.IntegerField(default=0)),
                ('num_service_hours_db', models.IntegerField(default=0)),
                ('num_service_hours_hkn', models.IntegerField(default=0)),
                ('num_service_hours_external', models.IntegerField(default=0)),
                ('electee_interview', models.BooleanField(default=False)),
                ('electee_exam', models.BooleanField(default=False)),
                ('dues', models.BooleanField(default=False)),
                ('general_meetings_missed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('requirement', models.CharField(choices=[('A_UG_SOCIAL', 'Number Undergrad Socials'), ('B_G_SOCIAL', 'Number Grad Socials'), ('C_UG_TOTAL_HOURS', 'Undergrad Total Service Hours'), ('D_G_TOTAL_HOURS', 'Grad Total Service Hours'), ('E_UG_DB_HOURS', 'Max Undergrad dB Service Hours'), ('F_G_DB_HOURS', 'Max Grad dB Service Hours'), ('G_UG_EXTERNAL_HOURS', 'Max Undergrad External Service Hours'), ('H_G_EXTERNAL_HOURS', 'Max Grad External Service Hours'), ('I_SINGLE_SERVICE_EVENT_HOURS', 'Max Hours for a Single Service Event')], max_length=100, primary_key=True, serialize=False)),
                ('num_required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('dB', 'dB Cafe'), ('HKN', 'HKN'), ('Ex', 'External')], max_length=3)),
                ('service_name', models.CharField(max_length=100)),
                ('num_hours', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('electee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electeeManagement.Electee')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('electee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electeeManagement.Electee')),
            ],
        ),
    ]
