# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('requirement', models.CharField(choices=[('A_UG_SOCIAL', 'Number Undergrad Socials'), ('B_G_SOCIAL', 'Number Grad Socials'), ('C_UG_TOTAL_HOURS', 'Undergrad Total Service Hours'), ('D_G_TOTAL_HOURS', 'Grad Total Service Hours'), ('E_UG_DB_HOURS', 'Max Undergrad dB Service Hours'), ('F_G_DB_HOURS', 'Max Grad dB Service Hours'), ('G_UG_EXTERNAL_HOURS', 'Max Undergrad External Service Hours'), ('H_G_EXTERNAL_HOURS', 'Max Grad External Service Hours'), ('I_SINGLE_SERVICE_EVENT_HOURS', 'Max Hours for a Single Service Event')], max_length=100, primary_key=True, serialize=False)),
                ('num_required', models.IntegerField()),
            ],
        ),
    ]
