# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electeeManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electee',
            name='num_service_hours_approved',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='electee',
            name='num_service_hours_db',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='electee',
            name='num_service_hours_external',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='electee',
            name='num_service_hours_hkn',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='electee',
            name='num_service_hours_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='service_hours',
            name='num_hours',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
