# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160111_0119'),
        ('electeeManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electee',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Member')),
                ('num_socials_approved', models.IntegerField(default=0)),
                ('num_socials_total', models.IntegerField(default=0)),
                ('num_service_hours_approved', models.IntegerField(default=0)),
                ('num_service_hours_total', models.IntegerField(default=0)),
                ('num_service_hours_db', models.IntegerField(default=0)),
                ('num_service_hours_hkn', models.IntegerField(default=0)),
                ('num_service_hours_external', models.IntegerField(default=0)),
                ('electee_interview', models.BooleanField(default=False)),
                ('electee_exam', models.BooleanField(default=False)),
                ('dues', models.BooleanField(default=False)),
                ('general_meetings_missed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('dB', 'dB Cafe'), ('HKN', 'HKN'), ('Ex', 'External')], max_length=3)),
                ('service_name', models.CharField(max_length=100)),
                ('num_hours', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('electee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electeeManagement.Electee')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('electee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electeeManagement.Electee')),
            ],
        ),
    ]
