# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('uniqname', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Electee'), ('O', 'Officer')], default='E', max_length=1)),
                ('major', models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('CE', 'Computer Engineering'), ('EE', 'Electrical Engineering')], max_length=2, null=True)),
                ('edu_level', models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('GR', 'Graduate'), ('AL', 'Alumni')], max_length=2, null=True)),
                ('expected_grad_date', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path)),
                ('resume', models.FileField(blank=True, null=True, upload_to=users.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('dB', 'dB Cafe'), ('HKN', 'HKN'), ('Ex', 'External')], max_length=3)),
                ('service_name', models.CharField(max_length=100)),
                ('num_hours', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Electee',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Member')),
                ('num_socials_approved', models.IntegerField(default=0)),
                ('num_socials_total', models.IntegerField(default=0)),
                ('num_service_hours_approved', models.IntegerField(default=0)),
                ('num_service_hours_total', models.IntegerField(default=0)),
                ('num_service_hours_db', models.IntegerField(default=0)),
                ('num_service_hours_hkn', models.IntegerField(default=0)),
                ('num_service_hours_external', models.IntegerField(default=0)),
                ('electee_interview', models.BooleanField(default=False)),
                ('electee_exam', models.BooleanField(default=False)),
                ('dues', models.BooleanField(default=False)),
                ('general_meetings_missed', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='social',
            name='electee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Electee'),
        ),
        migrations.AddField(
            model_name='service_hours',
            name='electee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Electee'),
        ),
    ]
