# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='uniqname',
            field=models.CharField(default='NotAName', max_length=8),
            preserve_default=False,
        ),
    ]
