# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20151221_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expected_grad_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='major',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('CE', 'Computer Engineering'), ('EE', 'Electrical Engineering')], max_length=2, null=True),
        ),
    ]
