# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20151221_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='edu_level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('GR', 'Graduate'), ('AL', 'Alumni')], max_length=2, null=True),
        ),
    ]
