# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_member_edu_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=users.models.user_directory_path),
        ),
    ]
