# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20151223_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
    ]
