# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Blog text')),
                ('author', models.CharField(max_length=120, verbose_name='Author')),
                ('publicationDate', models.DateField(verbose_name='Publication Date')),
            ],
        ),
    ]
