# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eecSpeaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publicationDate',
            field=models.DateField(null=True, verbose_name='Publication Date'),
        ),
    ]
